name: "Push to SSH"
description: "Push built source to SSH"
inputs:
  source:
    description: "Source directory"
    required: false
    default: 'source'
  built:
    description: "Previous build directory (needs to be repo and have a remote)"
    required: false
    default: 'built'
  env-host:
    description: "Env Host"
    required: true
    default: ''
  env-port:
    description: "Env Port"
    required: true
    default: '22'
  env-user:
    description: "Env User"
    required: true
    default: ''
  env-key:
    description: "Env SSH Key"
    required: false
    default: ''
  env-pass:
    description: "Env Password"
    required: false
    default: ''
  env-remote-root:
    description: "Env Remote Root"
    required: true
    default: ''
  ssh-flags:
    description: "SSH Flags to pass to the RSync command"
    required: false
    default: ''
  ssh-shell-params:
    description: "Parameters to be passed to the SSH shell command"
    required: false
    default: ''
  ssh-extra-options:
    description: "Extra options for the RSync command"
    required: false
    default: ''
  force-ignore:
    description: "Force ignore files"
    required: false
    default: |
      /auth.json
      /vendor/*
      !/vendor/composer
      /vendor/composer/*
      !/vendor/composer/installers
      !/vendor/composer/installed.json
  ssh-ignore:
    description: "Force ignore files"
    required: false
    default: |
      .git
      /*.log
      /uploads/
      /upgrade/
      /vendor/**
      /auth.json
      /composer.json
      /composer.lock
      /object-cache.php
      /db.php
  disable-consistency-check:
    description: Do not do a consistency check and complete the workflow regardless.
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Preparing built assets :large_yellow_circle:"

    - name: Build To GIT
      id: 'build-to-git'
      uses: saucal/action-build-to-git@v1
      with:
        from: ${{ inputs.source }}
        path: ${{ inputs.built }}
        defer-push: "true"
        force-ignore: ${{ inputs.force-ignore }}

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Pushing to SSH :large_yellow_circle:"

    - name: Define manifest to use
      if: "${{ inputs.disable-consistency-check != 'true' }}"
      id: manifest-load
      shell: bash
      run: |
        {
          echo 'manifest<<EOF_MANIFEST'
          echo "${{ steps.build-to-git.outputs.manifest }}"
          echo 'EOF_MANIFEST'
        } >> $GITHUB_OUTPUT

    - name: Deploy to SSH
      id: 'deploy-to-ssh'
      uses: saucal/action-deploy-ssh@v1
      with:
        manifest: "${{ steps.manifest-load.outputs.manifest }}"
        env-host: ${{ inputs.env-host }}
        env-port: ${{ inputs.env-port }}
        env-user: ${{ inputs.env-user }}
        env-key: ${{ inputs.env-key }}
        env-pass: ${{ inputs.env-pass }}
        env-local-root: ${{ inputs.built }}
        env-remote-root: ${{ inputs.env-remote-root }}
        force-ignore: ${{ inputs.ssh-ignore }}
        ssh-flags: ${{ inputs.ssh-flags }}
        ssh-shell-params: ${{ inputs.ssh-shell-params }}
        ssh-extra-options: ${{ inputs.ssh-extra-options }}

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Pushing to GIT :large_yellow_circle:"

    - name: Push to GIT
      id: 'push-to-git'
      uses: saucal/action-build-to-git@v1
      with:
        path: ${{ inputs.built }}
        do-push: "true"
