name: "Push to SSH"
description: "Push built source to SSH"
inputs:
  source:
    description: "Source directory"
    required: false
    default: 'source'
  built:
    description: "Previous build directory (needs to be repo and have a remote)"
    required: false
    default: 'built'
  env-host:
    description: "Env Host"
    required: true
    default: ''
  env-port:
    description: "Env Port"
    required: true
    default: ''
  env-user:
    description: "Env User"
    required: true
    default: ''
  env-key:
    description: "Env SSH Key"
    required: true
    default: ''
  env-remote-root:
    description: "Env Remote Root"
    required: true
    default: ''
  ssh-flags:
    description: "SSH Flags to pass to the RSync command"
    required: false
    default: 'azvrn'
  ssh-shell-params:
    description: "Parameters to be passed to the SSH shell command"
    required: false
    default: ''
  ssh-extra-options:
    description: "Extra options for the RSync command"
    required: false
    default: ''
  force-ignore:
    description: "Force ignore files"
    required: false
    default: |
      /auth.json
      /vendor/*
      !/vendor/composer
      /vendor/composer/*
      !/vendor/composer/installers
      !/vendor/composer/installed.json
  ssh-ignore:
    description: "Force ignore files"
    required: false
    default: |
      .git
      uploads/
      /vendor/**
      /auth.json
      /composer.json
      /composer.lock
  full-deployment:
    description: "Force full deployment"
    required: false
    default: "${{ github.event_name != 'push' }}"
    
runs:
  using: "composite"
  steps:
    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Preparing built assets :large_yellow_circle:"

    - name: Build To GIT
      id: 'build-to-git'
      uses: saucal/action-build-to-git@v1
      with:
        from: ${{ inputs.source }}
        path: ${{ inputs.built }}
        defer-push: "true"
        force-ignore: ${{ inputs.force-ignore }}

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Pushing to SSH :large_yellow_circle:"

    - name: Define manifest to use
      id: manifest-load
      shell: bash
      run: |
        {
          if [ "${{ inputs.full-deployment }}" == "true" ]; then
            echo 'manifest<<EOF_MANIFEST'
            echo "${{ steps.build-to-git.outputs.manifest-full }}"
            echo 'EOF_MANIFEST'
          else
            echo 'manifest<<EOF_MANIFEST'
            echo "${{ steps.build-to-git.outputs.manifest }}"
            echo 'EOF_MANIFEST'
          fi
        } >> $GITHUB_OUTPUT
    
    - name: Mutate manifest for rsync
      shell: bash
      run: |
        sed -i -E "s/^[+-] //" "${{ steps.manifest-load.outputs.manifest }}"

    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
          mkdir -p /home/runner/.ssh
          echo "${{ inputs.env-key }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions

    - name: Deploy to SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      id: 'deploy-to-ssh'
      uses: saucal/action-deploy-ssh@v1
      with:
        manifest: "${{ steps.manifest-load.outputs.manifest }}"
        env-host: ${{ inputs.env-host }}
        env-port: ${{ inputs.env-port }}
        env-user: ${{ inputs.env-user }}
        env-local-root: ${{ inputs.built }}
        env-remote-root: ${{ inputs.env-remote-root }}
        force-ignore: ${{ inputs.ssh-ignore }}
        ssh-flags: ${{ inputs.ssh-flags }}
        ssh-shell-params: ${{ inputs.ssh-shell-params }}
        ssh-extra-options: ${{ inputs.ssh-extra-options }}

    - name: Consistency check
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      uses: saucal/action-deploy-ssh@v1
      with:
        env-host: ${{ inputs.env-host }}
        env-port: ${{ inputs.env-port }}
        env-user: ${{ inputs.env-user }}
        env-local-root: ${{ inputs.built }}
        env-remote-root: ${{ inputs.env-remote-root }}
        force-ignore: ${{ inputs.ssh-ignore }}
        ssh-flags: ${{ inputs.ssh-flags }}
        ssh-shell-params: ${{ inputs.ssh-shell-params }}
        ssh-extra-options: ${{ inputs.ssh-extra-options }}
        consistency-check: true

    - name: Set message
      uses: saucal/action-slack-notification@v1
      with:
        status: "Pushing to GIT :large_yellow_circle:"

    - name: Push to GIT
      id: 'push-to-git'
      uses: saucal/action-build-to-git@v1
      with:
        path: ${{ inputs.built }}
        do-push: "true"
